export const EXAMPLE_CODE_LINE_HEIGHT = 22;
export const EXAMPLE_IFRAME_MIN_HEIGHT = 32;
export const EXAMPLE_IFRAME_MARGIN = 20;
export const EDITOR_SCROLLBAR_SIZE = 12;
export const EDITOR_PADDING_TOP = 12;
export const EXAMPLE_MAX_HEIGHT =
  EXAMPLE_CODE_LINE_HEIGHT * 18 + EDITOR_PADDING_TOP + EDITOR_SCROLLBAR_SIZE;
export const EXAMPLE_MIN_HEIGHT =
  EXAMPLE_CODE_LINE_HEIGHT * 6 + EDITOR_PADDING_TOP + EDITOR_SCROLLBAR_SIZE;
