export const EXAMPLE_CODE_LINE_HEIGHT = 22;
export const EXAMPLE_IFRAME_MIN_HEIGHT = 32;
export const EXAMPLE_IFRAME_MARGIN = 64;
export const EXAMPLE_HEIGHT_THRESHOLD = EXAMPLE_CODE_LINE_HEIGHT * 20;
export const EDITOR_SCROLLBAR_SIZE = 12;
export const EDITOR_PADDING_TOP = 12;