name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: yarn

    # Fix `yarn install --frozen-lockfile` not working in monorepo.
    # https://github.com/yarnpkg/yarn/issues/5840#issuecomment-468782288
    - name: Get checksum before yarn install
      id: yarn-lock-check-before
      run: echo "::set-output name=sum::$(cksum yarn.lock)"

    - run: yarn install --frozen-lockfile

    - name: Get checksum after yarn install
      id: yarn-lock-check-after
      run: echo "::set-output name=sum::$(cksum yarn.lock)"

    - name: Exit if yarn.lock updated
      run: exit 1
      if: steps.yarn-lock-check-before.outputs.sum != steps.yarn-lock-check-after.outputs.sum

    - run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        force_orphan: true
      if: github.event_name == 'push'
